# Numerical parity with Kymatio (0.4.0.dev0, the reference implementation).
#
# Fixtures are generated by data-raw/make-fixtures.py and data-raw/make-fixtures.R.
# Neither Python nor Kymatio is needed to run these tests.

R_PSI <- sqrt(0.5)
SIGMA0 <- 0.1
ALPHA <- 5

fixture <- function(name) {
  readRDS(test_path("fixtures", name))
}

# Relative to the largest reference value, so that near-zero entries in a
# filter's tail are not judged on their own tiny scale.
expect_close <- function(got, want, tol = 1e-10, label = NULL) {
  got <- as.numeric(got)
  want <- as.numeric(want)
  expect_equal(length(got), length(want), label = label)
  scale <- max(abs(want))
  err <- if (scale > 0) max(abs(got - want)) / scale else max(abs(got - want))
  expect_lte(err, tol, label = label %||% "relative error")
}

`%||%` <- function(x, y) if (is.null(x)) y else x


test_that("filter bank helper functions match Kymatio", {
  fb <- fixture("kymatio-filter-bank.rds")
  s <- fb$scalars

  expect_close(vapply(s$sigmas, adaptive_choice_P, 0), s$P, 0)
  expect_close(vapply(s$Q, compute_xi_max, 0), s$xi_max, 1e-14)
  expect_close(
    vapply(s$Q, function(q) compute_sigma_psi(0.4, q, R_PSI), 0),
    s$sigma_psi, 1e-14
  )
  expect_close(
    mapply(get_max_dyadic_subsampling, s$pair_xi, s$pair_sigma,
           MoreArgs = list(alpha = ALPHA)),
    s$maxsub, 0
  )
})


test_that("individual Morlet and Gaussian filters match Kymatio", {
  fb <- fixture("kymatio-filter-bank.rds")

  for (i in seq_len(nrow(fb$morlet$meta))) {
    p <- fb$morlet$meta[i, ]
    expect_close(morlet_1d(p[1], p[2], p[3]), fb$morlet$values[[i]], 1e-12,
                 label = sprintf("morlet N=%d xi=%g", p[1], p[2]))
  }
  for (i in seq_len(nrow(fb$gauss$meta))) {
    p <- fb$gauss$meta[i, ]
    expect_close(gauss_1d(p[1], p[2]), fb$gauss$values[[i]], 1e-12,
                 label = sprintf("gauss N=%d sigma=%g", p[1], p[2]))
  }
  expect_close(
    vapply(seq_len(nrow(fb$tsupp$meta)), function(i) {
      compute_temporal_support(gauss_1d(fb$tsupp$meta[i, 1], fb$tsupp$meta[i, 2]))
    }, 0),
    fb$tsupp$values, 0
  )
})


test_that("the filter bank frequency schedule matches Kymatio", {
  fb <- fixture("kymatio-filter-bank.rds")
  for (i in seq_len(nrow(fb$generator$meta))) {
    J <- fb$generator$meta[i, 1]
    Q <- fb$generator$meta[i, 2]
    spec <- anden_generator(J, Q, SIGMA0, R_PSI)
    expect_close(spec$xi, fb$generator$xi[[i]], 1e-13,
                 label = sprintf("xi J=%d Q=%d", J, Q))
    expect_close(spec$sigma, fb$generator$sigma[[i]], 1e-13,
                 label = sprintf("sigma J=%d Q=%d", J, Q))
  }
})


test_that("the assembled filter banks match Kymatio at every resolution", {
  fb <- fixture("kymatio-filter-bank.rds")

  for (entry in fb$factory) {
    cfg <- entry$cfg
    N <- cfg[1]; J <- cfg[2]; Q <- c(cfg[3], cfg[4]); T <- cfg[5]
    tag <- sprintf("N=%d J=%d Q=%d/%d T=%d", N, J, Q[1], Q[2], T)
    got <- scattering_filter_factory(N, J, Q, T, ALPHA, R_PSI, SIGMA0)

    expect_equal(got$phi$j, entry$phi$j, label = paste("phi j", tag))
    expect_close(got$phi$sigma, entry$phi$sigma, 1e-14)
    expect_equal(length(got$phi$levels), length(entry$phi$levels),
                 label = paste("phi levels", tag))
    for (lev in seq_along(entry$phi$levels)) {
      expect_close(got$phi$levels[[lev]], entry$phi$levels[[lev]], 1e-12,
                   label = sprintf("phi level %d, %s", lev - 1L, tag))
    }

    for (ord in 1:2) {
      bank <- if (ord == 1L) got$psi1 else got$psi2
      want <- entry[[paste0("psi", ord)]]
      expect_equal(length(bank), length(want$xi),
                   label = sprintf("psi%d count, %s", ord, tag))
      expect_close(vapply(bank, `[[`, 0, "xi"), want$xi, 1e-13)
      expect_close(vapply(bank, `[[`, 0, "sigma"), want$sigma, 1e-13)
      expect_close(vapply(bank, `[[`, 0, "j"), want$j, 0)
      for (n in seq_along(bank)) {
        for (lev in seq_along(want$levels[[n]])) {
          expect_close(
            bank[[n]]$levels[[lev]], want$levels[[n]][[lev]], 1e-12,
            label = sprintf("psi%d[%d] level %d, %s", ord, n, lev - 1L, tag)
          )
        }
      }
    }
  }
})


test_that("full transforms match Kymatio", {
  cases <- fixture("kymatio-transforms.rds")

  for (case in cases) {
    tag <- sprintf("n=%d J=%d Q=%d/%d T=%s order=%d out=%s",
                   case$n, case$J, case$Q[1], case$Q[2],
                   if (is.null(case$T)) "NULL" else as.character(case$T),
                   case$max_order, case$out_type)

    op <- scattering_1d(
      n = case$n, J = case$J, Q = case$Q, T = case$T,
      max_order = case$max_order, stride = case$stride,
      out_type = case$out_type
    )
    S <- scat_transform(op, case$x)
    meta <- S$meta

    # Kymatio reports zero-based filter indices with NaN, coded here as -1.
    expect_close(meta$order, case$meta$order, 0, label = paste("order,", tag))
    expect_close(ifelse(is.na(meta$n1), -1, meta$n1 - 1), case$meta$n[, 1], 0,
                 label = paste("n1,", tag))
    expect_close(ifelse(is.na(meta$j1), -1, meta$j1), case$meta$j[, 1], 0,
                 label = paste("j1,", tag))
    expect_close(ifelse(is.na(meta$xi1), -1, meta$xi1), case$meta$xi[, 1], 1e-13,
                 label = paste("xi1,", tag))
    if (case$max_order >= 2L) {
      expect_close(ifelse(is.na(meta$n2), -1, meta$n2 - 1), case$meta$n[, 2], 0,
                   label = paste("n2,", tag))
      expect_close(ifelse(is.na(meta$j2), -1, meta$j2), case$meta$j[, 2], 0,
                   label = paste("j2,", tag))
      expect_close(ifelse(is.na(meta$xi2), -1, meta$xi2), case$meta$xi[, 2], 1e-13,
                   label = paste("xi2,", tag))
    }

    if (case$out_type == "array") {
      expect_equal(dim(S$coef)[1:2], dim(case$out), label = paste("dim,", tag))
      expect_close(S$coef[, , 1], case$out, 1e-10, label = paste("coefs,", tag))
    } else {
      expect_equal(length(S$coef), length(case$out), label = paste("npaths,", tag))
      for (k in seq_along(case$out)) {
        expect_close(S$coef[[k]][, 1], case$out[[k]], 1e-10,
                     label = sprintf("path %d, %s", k, tag))
      }
    }
  }
})
